---
title: "zoot_sdt_kt"
author: "Karen Tian"
date: "2025-05-07"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(warning = FALSE, message = FALSE) 
suppressPackageStartupMessages(library(tidyverse))
library(tidyverse)
library(lme4)
library(ez) # ANOVAs
# library(car)

knitr::opts_chunk$set(echo = TRUE)

#### anova setup #### 
options(contrasts=c("contr.sum","contr.poly"))

#### load data #### 
wd <- getwd()
analysisName = 'zoot_sdt_kt'
dataName <- sprintf("/Users/kantian/Dropbox/GitHub/ZOOT/kt_analysis/%s.csv", analysisName)
data <- read.csv(dataName)

#### Change to categorical vars ####
data$SID <- factor(data$SID) 
# data$nonTargetContrast <- factor(data$nonTargetContrast)

# factorize non-target
data <- data %>%
  mutate(
    nonTargetContrast = case_when(
      nonTargetContrast == 1~ "NTP",
      nonTargetContrast == 2 ~ "NTA",
      TRUE ~ NA_character_  # in case there are other values
    ),
    nonTargetContrast = factor(nonTargetContrast, levels = c("NTP", "NTA"), ordered = FALSE)
  )

# factorize target
data <- data %>%
  mutate(
    target = case_when(
      target == 1 ~ "T1",
      target == 2 ~ "T2",
      TRUE ~ NA_character_  # in case there are other values
    ),
    target = factor(target, levels = c("T1", "T2"), ordered = TRUE)
  )

# factorize validity
data <- data %>%
  mutate(
    validity = case_when(
      validity == 1 ~ "valid",
      validity == 2 ~ "neutral",
      validity == 3 ~ "invalid",
      TRUE ~ NA_character_  # in case there are other values
    ),
    validity = factor(validity, levels = c("valid","neutral","invalid"), ordered = TRUE)
  )
```

```{r anova_disSS, echo = TRUE}
m_anova = ezANOVA(
  data = data,
  dv = .(dis_dp_SS),
  wid = .(SID),
  within = .(validity,target,nonTargetContrast),
  detailed = TRUE,
  )
knitr::kable(m_anova, digits=3, caption=sprintf("Discrimination d'' SS"))

## Summary statistics (by validity)
d <- data %>% group_by(validity) %>% 
  summarise(mean=mean(dis_dp_SS), sd=sd(dis_dp_SS), n=n_distinct(SID)) %>% mutate(se = sd / sqrt(n),
         ci.lower = mean - 1.96 * se,
         ci.upper = mean + 1.96 * se)
knitr::kable(d, digits=3, caption=sprintf("Discrimination d' SS summary by validity"))

## Summary statistics (all)
d <- data %>% 
  summarise(mean=mean(dis_dp_SS), sd=sd(dis_dp_SS), n=n_distinct(SID)) %>% mutate(se = sd / sqrt(n),
         ci.lower = mean - 1.96 * se,
         ci.upper = mean + 1.96 * se)
knitr::kable(d, digits=3, caption=sprintf("Discrimination d' SS summary (all trials)"))

## Without competition

## T1 only 
d <- data %>% filter(target=="T1") %>% filter(nonTargetContrast=="NTA")
m_anova = ezANOVA(
  data = d,
  dv = .(dis_dp_SS),
  wid = .(SID),
  within = .(validity),
  detailed = TRUE,
  )
knitr::kable(m_anova, digits=3, caption=sprintf("Discrimination d'' SS, T1, non-target present"))


## T2 only 
d <- data %>% filter(target=="T2") %>% filter(nonTargetContrast=="NTA")
m_anova = ezANOVA(
  data = d,
  dv = .(dis_dp_SS),
  wid = .(SID),
  within = .(validity),
  detailed = TRUE,
  )
knitr::kable(m_anova, digits=3, caption=sprintf("Discrimination d'' SS, T2, non-target present"))
```

```{r anova_detSS, echo = TRUE}
d <- data # %>% filter(target=="T1") %>% filter(nonTargetContrast==1)
m_anova = ezANOVA(
  data = d,
  dv = .(det_dp_SS),
  wid = .(SID),
  within = .(validity,target,nonTargetContrast),
  detailed = TRUE,
  )
knitr::kable(m_anova, digits=3, caption=sprintf("Detection d'' SS"))

## Summary statistics
d <- d %>% group_by(validity) %>% 
  summarise(mean=mean(det_dp_SS), sd=sd(det_dp_SS), n=n_distinct(SID)) %>% mutate(se = sd / sqrt(n),
         ci.lower = mean - 1.96 * se,
         ci.upper = mean + 1.96 * se)
knitr::kable(d, digits=3, caption=sprintf("Detection d' SS summary"))
```

```{r anova_detcSS, echo = TRUE}
# Detection criterion
d <- data # %>% filter(target=="T1") %>% filter(nonTargetContrast==1)
m_anova = ezANOVA(
  data = d,
  dv = .(det_c_SS),
  wid = .(SID),
  within = .(validity,target,nonTargetContrast),
  detailed = TRUE,
  )
knitr::kable(m_anova, digits=3, caption=sprintf("Detection criterion SS"))

## Summary statistics
d <- d %>% group_by(validity) %>% 
  summarise(mean=mean(det_c_SS), sd=sd(det_c_SS), n=n_distinct(SID)) %>% mutate(se = sd / sqrt(n),
         ci.lower = mean - 1.96 * se,
         ci.upper = mean + 1.96 * se)
knitr::kable(d, digits=3, caption=sprintf("Detection criterion SS summary"))

# non-target present by target
targetCols <- c("T1")
for (col in targetCols) {
  d <- data %>% filter(target==col) %>% filter(nonTargetContrast=="NTP")
  m_anova = ezANOVA(
    data = d,
    dv = .(det_c_SS),
    wid = .(SID),
    within = .(validity),
    detailed = TRUE,
  )
  knitr::kable(m_anova, digits=3, caption=sprintf("Detection criterion %s non-target present SS", col))
}
```




