---
title: "tazoot_swap_LMM_twoIncorrect"
author: Jenny
output: github_document
date: "2025-05-09"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(warning = FALSE, message = FALSE) 
suppressPackageStartupMessages(library(tidyverse))
library(tidyverse)
library(lme4)
library(car)
library(dplyr)
library(lmerTest)


knitr::opts_chunk$set(echo = TRUE)

#### anova setup #### 
options(contrasts=c("contr.sum","contr.poly"))

#### load data #### 
wd <- getwd()
analysisName = 'tazoot_twoIncorrect_errSwapAcc'
dataName <- sprintf("/Users/jennymotzer/Documents/GitHub/ZOOT/stats/%s.csv", analysisName)
data <- read.csv(dataName)
# removes NaN rows from data 
data_clean <- data[!is.nan(data$twoIncorrect), ]
data <- data_clean
#### Change to categorical vars ####
data$SID <- factor(data$SID)
data$targetContrast <- factor(data$targetContrast, levels = c("1", "0"), ordered = TRUE)
data$nontargetContrast <- factor(data$nontargetContrast, levels = c("1", "0"), ordered = TRUE)
data$Target <- factor(data$Target, levels = c("1", "2"), ordered = TRUE)
data$Validity <- factor(data$Validity,levels = c("1", "2", "3"),ordered = TRUE)

### Plotting setup #### 
colors = c("#F8A299","#CCCCCC","#98E6A1")
attComparison <- list( c("1","3"), c("1","2"), c("2","3") )

significance <- list(cutpoints = c(0, 0.0001, 0.001, 0.01, 0.05, Inf),
symbols = c("****", "***", "**", "*", "ns"))

```

```{r swap group means}
## Summary statistics
d <- data %>% group_by(Validity, Target, targetContrast, nontargetContrast) %>% 
  summarise(mean=mean(twoIncorrect), sd=sd(twoIncorrect), n=n_distinct(SID)) %>% mutate(se = sd / sqrt(n),
         ci.lower = mean - 1.96 * se,
         ci.upper = mean + 1.96 * se)
knitr::kable(d, digits=3, caption=sprintf("twoIncorrect swap"))
```

```{r swapPlot}
library(ggplot2)
d <- data %>%
  mutate(TNTC = paste0("T", targetContrast, "_N", nontargetContrast))
ggplot(d, aes(x = Validity, y = twoIncorrect, color = TNTC)) + 
  geom_point() + stat_summary(
    fun = "mean",
    geom = "point",
    color = "red",
    size = 4
  ) +
  facet_grid(~Target) +
  theme_minimal()
```
# full model
## combined contrast
```{r swap combined contrast}
d <- data %>% mutate(combinedContrast = paste(targetContrast, nontargetContrast, sep = "_"))
d <- d %>%
  mutate(combinedContrast = factor(combinedContrast,
                                   levels =  c("1_1", "1_0", "0_1"),
                                   ordered = TRUE))
swap.lmm.lme4 <- lmer(twoIncorrect ~ Validity * Target * combinedContrast + (1|SID), data = d)
summary(swap.lmm.lme4)
aov.swap <- Anova(swap.lmm.lme4)
print(aov.swap)
```
## targetContrast and nontargetContrast
```{r swap uncombined contrast}
d <- data 
swap.lmm.lme4 <- lmer(twoIncorrect ~ Validity * Target * targetContrast * nontargetContrast + (1|SID), data = d)
summary(swap.lmm.lme4)
aov.swap <- Anova(swap.lmm.lme4)
print(aov.swap)
```
## T1
```{r swap T1}
d <- data %>% filter(Target==1)
swapT1.lmm.lme4 <- lmer(twoIncorrect ~ Validity * targetContrast * nontargetContrast + (1|SID), data = d)
summary(swapT1.lmm.lme4)
aov.swapT1 <- Anova(swapT1.lmm.lme4)
print(aov.swapT1)
```
## T2
```{r swap T2}
d <- data %>% filter(Target==2)
swapT2.lmm.lme4 <- lmer(twoIncorrect ~ Validity * targetContrast * nontargetContrast + (1|SID), data = d)
summary(swapT2.lmm.lme4)
aov.swapT2 <- Anova(swapT2.lmm.lme4)
print(aov.swapT2)
```
## TP
```{r swap TP}
d <- data %>% filter(targetContrast==1)
swapTP.lmm.lme4 <- lmer(twoIncorrect ~ Validity * nontargetContrast + (1|SID), data = d)
summary(swapTP.lmm.lme4)
aov.swapTP <- Anova(swapTP.lmm.lme4)
print(aov.swapTP)
```
## TP T1
```{r swap TP T1}
d <- data %>% filter(Target==1, targetContrast==1)
swapTPT1.lmm.lme4 <- lmer(twoIncorrect ~ Validity * nontargetContrast + (1|SID), data = d)
summary(swapTPT1.lmm.lme4)
aov.swapTPT1 <- Anova(swapTPT1.lmm.lme4)
print(aov.swapTPT1)
```
## TP T2
```{r swap TP T2}
d <- data %>% filter(Target==2, targetContrast==1)
swapTPT2.lmm.lme4 <- lmer(twoIncorrect ~ Validity * nontargetContrast + (1|SID), data = d)
summary(swapTPT2.lmm.lme4)
aov.swapTPT2 <- Anova(swapTPT2.lmm.lme4)
print(aov.swapTPT2)
```
## TA
```{r swap TA}
d <- data %>% filter(targetContrast==0)
swapTA.lmm.lme4 <- lmer(twoIncorrect ~ Validity  * nontargetContrast + (1|SID), data = d)
summary(swapTA.lmm.lme4)
aov.swapTA <- Anova(swapTA.lmm.lme4)
print(aov.swapTA)
```
## TA T1
```{r swap TA T1}
d <- data %>% filter(Target==1, targetContrast==0)
swapTAT1.lmm.lme4 <- lmer(twoIncorrect ~ Validity * nontargetContrast + (1|SID), data = d)
summary(swapTAT1.lmm.lme4)
aov.swapTAT1 <- Anova(swapTAT1.lmm.lme4)
print(aov.swapTAT1)
```
## TA T2
```{r swap TA T2}
d <- data %>% filter(Target==2, targetContrast==0)
swapTAT2.lmm.lme4 <- lmer(twoIncorrect ~ Validity * nontargetContrast + (1|SID), data = d)
summary(swapTAT2.lmm.lme4)
aov.swapTAT2 <- Anova(swapTAT2.lmm.lme4)
print(aov.swapTAT2)
```
## NP
```{r swap NP}
d <- data %>% filter(nontargetContrast==1)
swapNP.lmm.lme4 <- lmer(twoIncorrect ~ Validity * targetContrast + (1|SID), data = d)
summary(swapNP.lmm.lme4)
aov.swapNP <- Anova(swapNP.lmm.lme4)
print(aov.swapNP)
```
## NP T1
```{r swap NP T1}
d <- data %>% filter(Target==1, nontargetContrast==1)
swapNPT1.lmm.lme4 <- lmer(twoIncorrect ~ Validity * targetContrast + (1|SID), data = d)
summary(swapNPT1.lmm.lme4)
aov.swapNPT1 <- Anova(swapNPT1.lmm.lme4)
print(aov.swapNPT1)
```
## NP T2
```{r swap NP T2}
d <- data %>% filter(Target==2,nontargetContrast==1)
swapNPT2.lmm.lme4 <- lmer(twoIncorrect ~ Validity * targetContrast + (1|SID), data = d)
summary(swapNPT2.lmm.lme4)
aov.swapNPT2 <- Anova(swapNPT2.lmm.lme4)
print(aov.swapNPT2)
```
## NA
```{r swap NA}
d <- data %>% filter(nontargetContrast==0)
swapNA.lmm.lme4 <- lmer(twoIncorrect ~ Validity  * targetContrast + (1|SID), data = d)
summary(swapNA.lmm.lme4)
aov.swapNA <- Anova(swapNA.lmm.lme4)
print(aov.swapNA)
```
## NA T1
```{r swap NA T1}
d <- data %>% filter(Target==1, nontargetContrast==0)
swapNAT1.lmm.lme4 <- lmer(twoIncorrect ~ Validity * targetContrast + (1|SID), data = d)
summary(swapNAT1.lmm.lme4)
aov.swapNAT1 <- Anova(swapNAT1.lmm.lme4)
print(aov.swapNAT1)
```
## NA T2
```{r swap NA T2}
d <- data %>% filter(Target==2, nontargetContrast==0)
swapNAT2.lmm.lme4 <- lmer(twoIncorrect ~ Validity * targetContrast + (1|SID), data = d)
summary(swapNAT2.lmm.lme4)
aov.swapNAT2 <- Anova(swapNAT2.lmm.lme4)
print(aov.swapNAT2)
```
## TPNP
```{r swap TPNP}
d <- data %>% filter(targetContrast==1, nontargetContrast==1)
swapTPNP.lmm.lme4 <- lmer(twoIncorrect ~ Validity * Target + (1|SID), data = d)
summary(swapTPNP.lmm.lme4)
aov.swapTPNP <- Anova(swapTPNP.lmm.lme4)
print(aov.swapTPNP)
```
## TPNA
```{r swap TPNA}
d <- data %>% filter(targetContrast==1, nontargetContrast==0)
swapTPNA.lmm.lme4 <- lmer(twoIncorrect ~ Validity * Target + (1|SID), data = d)
summary(swapTPNA.lmm.lme4)
aov.swapTPNA <- Anova(swapTPNA.lmm.lme4)
print(aov.swapTPNA)
```

## TANP
```{r swap TANP}
d <- data %>% filter(targetContrast==0, nontargetContrast==1)
swapTANP.lmm.lme4 <- lmer(twoIncorrect ~ Validity * Target + (1|SID), data = d)
summary(swapTANP.lmm.lme4)
aov.swapTANP <- Anova(swapTANP.lmm.lme4)
print(aov.swapTANP)
```

# validity
```{r swap validity only}
d <- data
swap_validity.lmm.lme4 <- lmer(twoIncorrect ~ Validity + (1|SID), data = d)
summary(swap_validity.lmm.lme4)
aov.swap_validity <- Anova(swap_validity.lmm.lme4)
print(aov.swap_validity)
```
## TP
```{r swap validity TP}
d <- data %>% filter(targetContrast==1)
swap_validityTP.lmm.lme4 <- lmer(twoIncorrect ~ Validity + (1|SID), data = d)
summary(swap_validityTP.lmm.lme4)
aov.swap_validityTP <- Anova(swap_validityTP.lmm.lme4)
print(aov.swap_validityTP)
```
### T1
```{r swap validity TP T1}
d <- data %>% filter(targetContrast==1, Target==1)
swap_validityTPT1.lmm.lme4 <- lmer(twoIncorrect ~ Validity + (1|SID), data = d)
summary(swap_validityTPT1.lmm.lme4)
aov.swap_validityTPT1 <- Anova(swap_validityTPT1.lmm.lme4)
print(aov.swap_validityTPT1)
```
### T2
```{r swap validity TP T2}
d <- data %>% filter(targetContrast==1, Target==2)
swap_validityTPT2.lmm.lme4 <- lmer(twoIncorrect ~ Validity + (1|SID), data = d)
summary(swap_validityTPT2.lmm.lme4)
aov.swap_validityTPT2 <- Anova(swap_validityTPT2.lmm.lme4)
print(aov.swap_validityTPT2)
```
## TA
```{r swap validity TA}
d <- data %>% filter(targetContrast==0)
swap_validityTA.lmm.lme4 <- lmer(twoIncorrect ~ Validity + (1|SID), data = d)
summary(swap_validityTA.lmm.lme4)
aov.swap_validityTA <- Anova(swap_validityTA.lmm.lme4)
print(aov.swap_validityTA)
```
### T1
```{r swap validity TA T1}
d <- data %>% filter(targetContrast==0, Target==1)
swap_validityTAT1.lmm.lme4 <- lmer(twoIncorrect ~ Validity + (1|SID), data = d)
summary(swap_validityTAT1.lmm.lme4)
aov.swap_validityTAT1 <- Anova(swap_validityTAT1.lmm.lme4)
print(aov.swap_validityTAT1)
```
### T2
```{r swap validity TA T2}
d <- data %>% filter(targetContrast==0, Target==2)
swap_validityTAT2.lmm.lme4 <- lmer(twoIncorrect ~ Validity + (1|SID), data = d)
summary(swap_validityTAT2.lmm.lme4)
aov.swap_validityTAT2 <- Anova(swap_validityTAT2.lmm.lme4)
print(aov.swap_validityTAT2)
```
## NP
```{r swap validity NP}
d <- data %>% filter(nontargetContrast==1)
swap_validityNP.lmm.lme4 <- lmer(twoIncorrect ~ Validity + (1|SID), data = d)
summary(swap_validityNP.lmm.lme4)
aov.swap_validityNP <- Anova(swap_validityNP.lmm.lme4)
print(aov.swap_validityNP)
```
### T1
```{r swap validity NP T1}
d <- data %>% filter(nontargetContrast==1, Target==1)
swap_validityNPT1.lmm.lme4 <- lmer(twoIncorrect ~ Validity + (1|SID), data = d)
summary(swap_validityNPT1.lmm.lme4)
aov.swap_validityNPT1 <- Anova(swap_validityNPT1.lmm.lme4)
print(aov.swap_validityNPT1)
```
### T2
```{r swap validity NP T2}
d <- data %>% filter(nontargetContrast==1, Target==2)
swap_validityNPT2.lmm.lme4 <- lmer(twoIncorrect ~ Validity + (1|SID), data = d)
summary(swap_validityNPT2.lmm.lme4)
aov.swap_validityNPT2 <- Anova(swap_validityNPT2.lmm.lme4)
print(aov.swap_validityNPT2)
```
## NA
```{r swap validity NA}
d <- data %>% filter(nontargetContrast==0)
swap_validityNA.lmm.lme4 <- lmer(twoIncorrect ~ Validity + (1|SID), data = d)
summary(swap_validityNA.lmm.lme4)
aov.swap_validityNA <- Anova(swap_validityNA.lmm.lme4)
print(aov.swap_validityNA)
```
### T1
```{r swap validity NA T1}
d <- data %>% filter(nontargetContrast==0, Target==1)
swap_validityNAT1.lmm.lme4 <- lmer(twoIncorrect ~ Validity + (1|SID), data = d)
summary(swap_validityNAT1.lmm.lme4)
aov.swap_validityNAT1 <- Anova(swap_validityNAT1.lmm.lme4)
print(aov.swap_validityNAT1)
```
### T2
```{r swap validity NA T2}
d <- data %>% filter(nontargetContrast==0, Target==2)
swap_validityNAT2.lmm.lme4 <- lmer(twoIncorrect ~ Validity + (1|SID), data = d)
summary(swap_validityNAT2.lmm.lme4)
aov.swap_validityNAT2 <- Anova(swap_validityNAT2.lmm.lme4)
print(aov.swap_validityNAT2)
```
## TPNP
```{r swap validity TPNP}
d <- data %>% filter(targetContrast==1, nontargetContrast==1)
swap_validityTPNP.lmm.lme4 <- lmer(twoIncorrect ~ Validity + (1|SID), data = d)
summary(swap_validityTPNP.lmm.lme4)
aov.swap_validityTPNP <- Anova(swap_validityTPNP.lmm.lme4)
print(aov.swap_validityTPNP)
```
### T1
```{r swap validity TPNP T1}
d <- data %>% filter(targetContrast==1, nontargetContrast==1, Target==1)
swap_validityTPNP_T1.lmm.lme4 <- lmer(twoIncorrect ~ Validity + (1|SID), data = d)
summary(swap_validityTPNP_T1.lmm.lme4)
aov.swap_validityTPNP_T1 <- Anova(swap_validityTPNP_T1.lmm.lme4)
print(aov.swap_validityTPNP_T1)
```
### T2
```{r swap validity TPNP T2}
d <- data %>% filter(targetContrast==1, nontargetContrast==1, Target==2)
swap_validityTPNP_T2.lmm.lme4 <- lmer(twoIncorrect ~ Validity + (1|SID), data = d)
summary(swap_validityTPNP_T2.lmm.lme4)
aov.swap_validityTPNP_T2 <- Anova(swap_validityTPNP_T2.lmm.lme4)
print(aov.swap_validityTPNP_T2)
```
## TANP
```{r swap validity TANP}
d <- data %>% filter(targetContrast==0, nontargetContrast==1)
swap_validityTANP.lmm.lme4 <- lmer(twoIncorrect ~ Validity + (1|SID), data = d)
summary(swap_validityTANP.lmm.lme4)
aov.swap_validityTANP <- Anova(swap_validityTANP.lmm.lme4)
print(aov.swap_validityTANP)
```
### T1
```{r swap validity TANP T1}
d <- data %>% filter(targetContrast==0, nontargetContrast==1, Target==1)
swap_validityTANP_T1.lmm.lme4 <- lmer(twoIncorrect ~ Validity + (1|SID), data = d)
summary(swap_validityTANP_T1.lmm.lme4)
aov.swap_validityTANP_T1 <- Anova(swap_validityTANP_T1.lmm.lme4)
print(aov.swap_validityTANP_T1)
```
### T2
```{r swap validity TANP T2}
d <- data %>% filter(targetContrast==0, nontargetContrast==1, Target==2)
swap_validityTANP_T2.lmm.lme4 <- lmer(twoIncorrect ~ Validity + (1|SID), data = d)
summary(swap_validityTANP_T2.lmm.lme4)
aov.swap_validityTANP_T2 <- Anova(swap_validityTANP_T2.lmm.lme4)
print(aov.swap_validityTANP_T2)
```
## TPNA
```{r swap validity TPNA}
d <- data %>% filter(targetContrast==1, nontargetContrast==0)
swap_validityTPNA.lmm.lme4 <- lmer(twoIncorrect ~ Validity + (1|SID), data = d)
summary(swap_validityTPNA.lmm.lme4)
aov.swap_validityTPNA <- Anova(swap_validityTPNA.lmm.lme4)
print(aov.swap_validityTPNA)
```
### T1
```{r swap validity TPNA T1}
d <- data %>% filter(targetContrast==1, nontargetContrast==1, Target==1)
swap_validityTPNA_T1.lmm.lme4 <- lmer(twoIncorrect ~ Validity + (1|SID), data = d)
summary(swap_validityTPNA_T1.lmm.lme4)
aov.swap_validityTPNA_T1 <- Anova(swap_validityTPNA_T1.lmm.lme4)
print(aov.swap_validityTPNA_T1)
```
### T2
```{r swap validity TPNA T2}
d <- data %>% filter(targetContrast==1, nontargetContrast==1, Target==2)
swap_validityTPNA_T2.lmm.lme4 <- lmer(twoIncorrect ~ Validity + (1|SID), data = d)
summary(swap_validityTPNA_T2.lmm.lme4)
aov.swap_validityTPNA_T2 <- Anova(swap_validityTPNA_T2.lmm.lme4)
print(aov.swap_validityTPNA_T2)
```
## T1
```{r swap validity T1}
d <- data %>% filter(Target==1)
swap_validityT1.lmm.lme4 <- lmer(twoIncorrect ~ Validity + (1|SID), data = d)
summary(swap_validityT1.lmm.lme4)
aov.swap_validityT1 <- Anova(swap_validityT1.lmm.lme4)
print(aov.swap_validityT1)
```
## T2
```{r swap validity T2}
d <- data %>% filter(Target==2)
swap_validityT2.lmm.lme4 <- lmer(twoIncorrect ~ Validity + (1|SID), data = d)
summary(swap_validityT2.lmm.lme4)
aov.swap_validityT2 <- Anova(swap_validityT2.lmm.lme4)
print(aov.swap_validityT2)
```

# target
```{r swap Target only}
d <- data
swap_target.lmm.lme4 <- lmer(twoIncorrect ~ Target + (1|SID), data = d)
summary(swap_target.lmm.lme4)
aov.swap_target <- Anova(swap_target.lmm.lme4)
print(aov.swap_target)
```
## TP
```{r swap target TP}
d <- data %>% filter(targetContrast==1)
swap_targetTP.lmm.lme4 <- lmer(twoIncorrect ~ Target + (1|SID), data = d)
summary(swap_targetTP.lmm.lme4)
aov.swap_targetTP <- Anova(swap_targetTP.lmm.lme4)
print(aov.swap_targetTP)
```
## TA
```{r swap target TA}
d <- data %>% filter(targetContrast==0)
swap_targetTA.lmm.lme4 <- lmer(twoIncorrect ~ Target + (1|SID), data = d)
summary(swap_targetTA.lmm.lme4)
aov.swap_targetTA <- Anova(swap_targetTA.lmm.lme4)
print(aov.swap_targetTA)
```
## NP
```{r swap target NP}
d <- data %>% filter(nontargetContrast==1)
swap_targetNP.lmm.lme4 <- lmer(twoIncorrect ~ Target + (1|SID), data = d)
summary(swap_targetNP.lmm.lme4)
aov.swap_targetNP <- Anova(swap_targetNP.lmm.lme4)
print(aov.swap_targetNP)
```
## NA
```{r swap target NA}
d <- data %>% filter(nontargetContrast==0)
swap_targetNA.lmm.lme4 <- lmer(twoIncorrect ~ Target + (1|SID), data = d)
summary(swap_targetNA.lmm.lme4)
aov.swap_targetNA <- Anova(swap_targetNA.lmm.lme4)
print(aov.swap_targetNA)
```
## TPNP
```{r swap target TPNP}
d <- data %>% filter(targetContrast==1, nontargetContrast==1)
swap_targetTPNP.lmm.lme4 <- lmer(twoIncorrect ~ Target + (1|SID), data = d)
summary(swap_targetTPNP.lmm.lme4)
aov.swap_targetTPNP <- Anova(swap_targetTPNP.lmm.lme4)
print(aov.swap_targetTPNP)
```
## TANP
```{r swap target TANP}
d <- data %>% filter(targetContrast==0, nontargetContrast==1)
swap_targetTANP.lmm.lme4 <- lmer(twoIncorrect ~ Target + (1|SID), data = d)
summary(swap_targetTANP.lmm.lme4)
aov.swap_targetTANP <- Anova(swap_targetTANP.lmm.lme4)
print(aov.swap_targetTANP)
```
## TPNA
```{r swap target TPNA}
d <- data %>% filter(targetContrast==1, nontargetContrast==0)
swap_targetTPNA.lmm.lme4 <- lmer(twoIncorrect ~ Target + (1|SID), data = d)
summary(swap_targetTPNA.lmm.lme4)
aov.swap_targetTPNA <- Anova(swap_targetTPNA.lmm.lme4)
print(aov.swap_targetTPNA)
```

# target contrast
```{r swap targetContrast only}
d <- data
swap_targetContrast.lmm.lme4 <- lmer(twoIncorrect ~ targetContrast + (1|SID), data = d)
summary(swap_targetContrast.lmm.lme4)
aov.swap_targetContrast <- Anova(swap_targetContrast.lmm.lme4)
print(aov.swap_targetContrast)
```
## T1
```{r swap targetContrast T1}
d <- data %>% filter(Target==1)
swap_targetContrastT1.lmm.lme4 <- lmer(twoIncorrect ~ targetContrast + (1|SID), data = d)
summary(swap_targetContrastT1.lmm.lme4)
aov.swap_targetContrastT1 <- Anova(swap_targetContrastT1.lmm.lme4)
print(aov.swap_targetContrastT1)
```
## T2
```{r swap targetContrast T2}
d <- data %>% filter(Target==2)
swap_targetContrastT2.lmm.lme4 <- lmer(twoIncorrect ~ targetContrast + (1|SID), data = d)
summary(swap_targetContrastT2.lmm.lme4)
aov.swap_targetContrastT2 <- Anova(swap_targetContrastT2.lmm.lme4)
print(aov.swap_targetContrastT2)
```
## NP
```{r swap targetContrast NP}
d <- data %>% filter(nontargetContrast==1)
swap_targetContrastNP.lmm.lme4 <- lmer(twoIncorrect ~ targetContrast + (1|SID), data = d)
summary(swap_targetContrastNP.lmm.lme4)
aov.swap_targetContrastNP <- Anova(swap_targetContrastNP.lmm.lme4)
print(aov.swap_targetContrastNP)
```
### T1
```{r swap targetContrast NP T1}
d <- data %>% filter(nontargetContrast==1, Target==1)
swap_targetContrastNPT1.lmm.lme4 <- lmer(twoIncorrect ~ targetContrast + (1|SID), data = d)
summary(swap_targetContrastNPT1.lmm.lme4)
aov.swap_targetContrastNPT1 <- Anova(swap_targetContrastNPT1.lmm.lme4)
print(aov.swap_targetContrastNPT1)
```
### T2
```{r swap targetContrast NP T2}
d <- data %>% filter(nontargetContrast==1, Target==2)
swap_targetContrastNPT2.lmm.lme4 <- lmer(twoIncorrect ~ targetContrast + (1|SID), data = d)
summary(swap_targetContrastNPT2.lmm.lme4)
aov.swap_targetContrastNPT2 <- Anova(swap_targetContrastNPT2.lmm.lme4)
print(aov.swap_targetContrastNPT2)
```
## NA
```{r swap targetContrast NA}
d <- data %>% filter(nontargetContrast==0)
swap_targetContrastNA.lmm.lme4 <- lmer(twoIncorrect ~ targetContrast + (1|SID), data = d)
summary(swap_targetContrastNA.lmm.lme4)
aov.swap_targetContrastNA <- Anova(swap_targetContrastNA.lmm.lme4)
print(aov.swap_targetContrastNA)
```
### T1
```{r swap targetContrast NA T1}
d <- data %>% filter(nontargetContrast==0, Target==1)
swap_targetContrastNAT1.lmm.lme4 <- lmer(twoIncorrect ~ targetContrast + (1|SID), data = d)
summary(swap_targetContrastNAT1.lmm.lme4)
aov.swap_targetContrastNAT1 <- Anova(swap_targetContrastNAT1.lmm.lme4)
print(aov.swap_targetContrastNAT1)
```
### T2
```{r swap targetContrast NA T2}
d <- data %>% filter(nontargetContrast==0, Target==2)
swap_targetContrastNAT2.lmm.lme4 <- lmer(twoIncorrect ~ targetContrast + (1|SID), data = d)
summary(swap_targetContrastNAT2.lmm.lme4)
aov.swap_targetContrastNAT2 <- Anova(swap_targetContrastNAT2.lmm.lme4)
print(aov.swap_targetContrastNAT2)
```
# nontarget contrast
```{r swap nontargetContrast only}
d <- data
swap_nontargetContrast.lmm.lme4 <- lmer(twoIncorrect ~ nontargetContrast + (1|SID), data = d)
summary(swap_targetContrast.lmm.lme4)
aov.swap_nontargetContrast <- Anova(swap_nontargetContrast.lmm.lme4)
print(aov.swap_nontargetContrast)
```
## T1
```{r swap nontargetContrast T1}
d <- data %>% filter(Target==1)
swap_nontargetContrastT1.lmm.lme4 <- lmer(twoIncorrect ~ nontargetContrast + (1|SID), data = d)
summary(swap_nontargetContrastT1.lmm.lme4)
aov.swap_nontargetContrastT1 <- Anova(swap_nontargetContrastT1.lmm.lme4)
print(aov.swap_nontargetContrastT1)
```
## T2
```{r swap nontargetContrast T2}
d <- data %>% filter(Target==2)
swap_nontargetContrastT2.lmm.lme4 <- lmer(twoIncorrect ~ nontargetContrast + (1|SID), data = d)
summary(swap_nontargetContrastT2.lmm.lme4)
aov.swap_nontargetContrastT2 <- Anova(swap_nontargetContrastT2.lmm.lme4)
print(aov.swap_nontargetContrastT2)
```
## TP
```{r swap nontargetContrast TP}
d <- data %>% filter(targetContrast==1)
swap_nontargetContrastTP.lmm.lme4 <- lmer(twoIncorrect ~ nontargetContrast + (1|SID), data = d)
summary(swap_nontargetContrastTP.lmm.lme4)
aov.swap_nontargetContrastTP <- Anova(swap_nontargetContrastTP.lmm.lme4)
print(aov.swap_nontargetContrastTP)
```
### T1
```{r swap nontargetContrast TP T1}
d <- data %>% filter(targetContrast==1, Target==1)
swap_nontargetContrastTPT1.lmm.lme4 <- lmer(twoIncorrect ~ nontargetContrast + (1|SID), data = d)
summary(swap_nontargetContrastTPT1.lmm.lme4)
aov.swap_nontargetContrastTPT1 <- Anova(swap_nontargetContrastTPT1.lmm.lme4)
print(aov.swap_nontargetContrastTPT1)
```
### T2
```{r swap nontargetContrast TP T2}
d <- data %>% filter(targetContrast==1, Target==2)
swap_nontargetContrastTPT2.lmm.lme4 <- lmer(twoIncorrect ~ nontargetContrast + (1|SID), data = d)
summary(swap_nontargetContrastTPT2.lmm.lme4)
aov.swap_nontargetContrastTPT2 <- Anova(swap_nontargetContrastTPT2.lmm.lme4)
print(aov.swap_nontargetContrastTPT2)
```
## TA
```{r swap nontargetContrast TA}
d <- data %>% filter(targetContrast==0)
swap_nontargetContrastTA.lmm.lme4 <- lmer(twoIncorrect ~ nontargetContrast + (1|SID), data = d)
summary(swap_nontargetContrastTA.lmm.lme4)
aov.swap_nontargetContrastTA <- Anova(swap_nontargetContrastTA.lmm.lme4)
print(aov.swap_nontargetContrastTA)
```
### T1
```{r swap nontargetContrast TA T1}
d <- data %>% filter(targetContrast==0, Target==1)
swap_nontargetContrastTAT1.lmm.lme4 <- lmer(twoIncorrect ~ nontargetContrast + (1|SID), data = d)
print(swap_nontargetContrastTAT1.lmm.lme4)
aov.swap_nontargetContrastTAT1 <- Anova(swap_nontargetContrastTAT1.lmm.lme4)
summary(aov.swap_nontargetContrastTAT1)
```
### T2
```{r swap nontargetContrast TA T2}
d <- data %>% filter(targetContrast==0, Target==2)
swap_nontargetContrastTAT2.lmm.lme4 <- lmer(twoIncorrect ~ nontargetContrast + (1|SID), data = d)
summary(swap_nontargetContrastTAT2.lmm.lme4)
aov.swap_nontargetContrastTAT2 <- Anova(swap_nontargetContrastTAT2.lmm.lme4)
print(aov.swap_nontargetContrastTAT2)
```
