---
title: "tazoot_bayes_factor"
author: Jenny Motzer
output: github_document
date: "2025-06-12"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

knitr::opts_chunk$set(warning = FALSE, message = FALSE) 
suppressPackageStartupMessages(library(tidyverse))
library(ez)
library(foreach)
library(kableExtra)
library(ggplot2)
library(dplyr)
library(ggpubr)
library(lsr)
library(report)
library(BayesFactor)
library(rempsyc) # for t-tests in nice tables

knitr::opts_chunk$set(echo = TRUE)

#### anova setup #### 
options(contrasts=c("contr.sum","contr.poly"))

#### load data #### 
wd <- getwd()
analysisName = 'tazoot_Acc_RT'
dataName <- sprintf("/Users/jennymotzer/Documents/GitHub/ZOOT/stats/%s.csv", analysisName)
data <- read.csv(dataName)

#### Change to categorical vars ####
data$SID <- factor(data$SID)
data$targetContrast <- factor(data$targetContrast)
data$nontargetContrast <- factor(data$nontargetContrast)
data$Target <- factor(data$Target)
data$Validity <- factor(data$Validity)

### Plotting setup #### 
colors = c("#F8A299","#CCCCCC","#98E6A1")
attComparison <- list( c("1","3"), c("1","2"), c("2","3") )

significance <- list(cutpoints = c(0, 0.0001, 0.001, 0.01, 0.05, Inf),
symbols = c("****", "***", "**", "*", "ns"))
```

# full 
## interaction
```{r full_interaction_acc_Bayes_Factor}
d <- data
bf_full_interaction <- anovaBF(Acc ~ Validity * nontargetContrast * Target * targetContrast  + SID, data = data, whichRandom = "SID", progress = FALSE)
bf=sort(bf_full_interaction, decreasing = TRUE)
print(bf)
```
## main
```{r full_main_acc_Bayes_Factor}
d <- data
bf_full_main <- anovaBF(Acc ~ Validity + nontargetContrast * Target * targetContrast + SID, data = data, whichRandom = "SID", progress = FALSE)
bf_interaction <- bf_full_interaction / bf_full_main
print(bf_interaction)
```

# Target Contrast
## TP 
```{r TP_acc_Bayes_Factor}
d <- data%>% filter(targetContrast==1)
bf_full <- anovaBF(Acc ~ Validity * nontargetContrast * Target + SID, data = d, whichRandom = "SID", progress = FALSE)
bf_full=sort(bf_full, decreasing = TRUE)
print(bf_full)

bf_null <- anovaBF(Acc ~ Validity * Target, data = d, whichRandom = "SID", progress = FALSE)

# Compare the full and null model
#custom_bf <- bf_full/bf_null

# print(bf)
# plot(bf)
```
# plot
ggplot(d, aes(x=Validity, y=Acc))  # bar plot 
df_summary <- d %>% group_by(Validity) %>% summarise(
  mean=mean(Acc, na.rm=TRUE),
  sd=sd(Acc, na.rm=TRUE),
  n=n(),
  se=sd/sqrt(n)
  )
print(df_summary)
## TA
```{r TA_acc_Bayes_Factor}
d <- data%>% filter(targetContrast==0)
bf_TA <- anovaBF(Acc ~ Validity * Target * nontargetContrast + SID, data = data, whichRandom = "SID", progress = FALSE)
bf_TA <- sort(bf_TA, decreasing = TRUE)
print(bf_TA)
```

# Nontarget Contrast
## NP 
```{r NP_acc_Bayes_Factor}
d <- data%>% filter(nontargetContrast==1)
bf_NP <- anovaBF(Acc ~ Validity * Target + targetContrast + SID, data = data, whichRandom = "SID", progress = FALSE)
print(bf_NP)
```
## NA
```{r NA_acc_Bayes_Factor}
d <- data%>% filter(nontargetContrast==0)
bf_NA <- anovaBF(Acc ~ Validity * Target + targetContrast  + SID, data = data, whichRandom = "SID", progress = FALSE)
print(bf_NA)
```
