---
title: "tazoot_swap_chance"
author: Jenny Motzer
output: github_document
date: "2025-06-10"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

knitr::opts_chunk$set(warning = FALSE, message = FALSE) 
suppressPackageStartupMessages(library(tidyverse))
library(ez)
library(foreach)
library(kableExtra)
library(ggplot2)
library(dplyr)
library(ggpubr)
library(lsr)
library(report)
library(purrr)
library(tidyr)
library(broom)

library(rempsyc) # for t-tests in nice tables
knitr::opts_chunk$set(echo = TRUE)

#### anova setup #### 
options(contrasts=c("contr.sum","contr.poly"))

#### load data #### 
wd <- getwd()
analysisName = 'tazoot_twoIncorrect_errSwapAcc'
dataName <- sprintf("/Users/jennymotzer/Documents/GitHub/ZOOT/stats/%s.csv", analysisName)
data <- read.csv(dataName)
data_clean <- data[!is.nan(data$twoIncorrect), ]
data <- data_clean
#### Change to categorical vars ####
data$SID <- factor(data$SID)
data$targetContrast <- factor(data$targetContrast)
data$nontargetContrast <- factor(data$nontargetContrast)
data$Target <- factor(data$Target)
data$Validity <- factor(data$Validity)

### Plotting setup #### 
colors = c("#F8A299","#CCCCCC","#98E6A1")
attComparison <- list( c("1","3"), c("1","2"), c("2","3") )

significance <- list(cutpoints = c(0, 0.0001, 0.001, 0.01, 0.05, Inf),
symbols = c("****", "***", "**", "*", "ns"))
```

```{r swap TP}
d <- data 
dt <- d %>% filter(targetContrast == 1, nontargetContrast == 1)
t_test_result <-t.test(dt$twoIncorrect, mu=0.5) 
tidy_res <- tidy(t_test_result)
print(tidy_res)
```


```{r swap TPNP}
d <- data 
dt <- d %>% filter(targetContrast == 1, nontargetContrast == 1)
t_test_result <-t.test(dt$twoIncorrect, mu=0.5) 
tidy_res <- tidy(t_test_result)
print(tidy_res)
```


```{r swap TPNP T1}
d <- data 
dt <- d %>% filter(targetContrast == 1, nontargetContrast == 1)
t_test_result <-t.test(dt$twoIncorrect, mu=0.5) 
tidy_res <- tidy(t_test_result)
print(tidy_res)
```


