---
title: "tazoot_swap_LLM"
author: Jenny
output: github_document
date: "2025-04-30"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(warning = FALSE, message = FALSE) 
suppressPackageStartupMessages(library(tidyverse))
library(tidyverse)
library(lme4)
library(car)
library(dplyr)

knitr::opts_chunk$set(echo = TRUE)

#### anova setup #### 
options(contrasts=c("contr.sum","contr.poly"))

#### load data #### 
wd <- getwd()
analysisName = 'tazoot_point93_errSwapAcc'
dataName <- sprintf("/Users/jennymotzer/Documents/GitHub/ZOOT/stats/%s.csv", analysisName)
data <- read.csv(dataName)
# removes NaN rows from data 
data_clean <- data[!is.nan(data$point95_SwapAcc), ]
data <- data_clean
#### Change to categorical vars ####
data$SID <- factor(data$SID)
data$targetContrast <- factor(data$targetContrast, levels = c("1", "0"), ordered = TRUE)
data$nontargetContrast <- factor(data$nontargetContrast, levels = c("1", "0"), ordered = TRUE)
data$Target <- factor(data$Target, levels = c("1", "2"), ordered = TRUE)
data$Validity <- factor(data$Validity,levels = c("1", "2", "3"),ordered = TRUE)

### Plotting setup #### 
colors = c("#F8A299","#CCCCCC","#98E6A1")
attComparison <- list( c("1","3"), c("1","2"), c("2","3") )

significance <- list(cutpoints = c(0, 0.0001, 0.001, 0.01, 0.05, Inf),
symbols = c("****", "***", "**", "*", "ns"))

```

```{r swap}
d <- data
swap.lmm.lme4 <- lmer(point95_SwapAcc ~ Validity * Target * targetContrast * nontargetContrast + (1|SID), data = d)
summary(swap.lmm.lme4)
aov.swap <- Anova(swap.lmm.lme4)
```
# validity
```{r swap validity only}
d <- data
swap_validity.lmm.lme4 <- lmer(point95_SwapAcc ~ Validity + (1|SID), data = d)
summary(swap_validity.lmm.lme4)
aov.swap_validity <- Anova(swap_validity.lmm.lme4)
```
## TP
```{r swap validity TP}
d <- data %>% filter(targetContrast==1)
swap_validityTP.lmm.lme4 <- lmer(point95_SwapAcc ~ Validity + (1|SID), data = d)
summary(swap_validityTP.lmm.lme4)
aov.swap_validityTP <- Anova(swap_validityTP.lmm.lme4)
```
## TA
```{r swap validity TA}
d <- data %>% filter(targetContrast==0)
swap_validityTA.lmm.lme4 <- lmer(point95_SwapAcc ~ Validity + (1|SID), data = d)
summary(swap_validityTA.lmm.lme4)
aov.swap_validityTA <- Anova(swap_validityTA.lmm.lme4)
```
## TPNP
```{r swap validity TPNP}
d <- data %>% filter(targetContrast==1, nontargetContrast==1)
swap_validityTPNP.lmm.lme4 <- lmer(point95_SwapAcc ~ Validity + (1|SID), data = d)
summary(swap_validityTPNP.lmm.lme4)
aov.swap_validityTPNP <- Anova(swap_validityTPNP.lmm.lme4)
```
### T1
```{r swap validity TPNP T1}
d <- data %>% filter(targetContrast==1, nontargetContrast==1, Target==1)
swap_validityTPNP_T1.lmm.lme4 <- lmer(point95_SwapAcc ~ Validity + (1|SID), data = d)
summary(swap_validityTPNP_T1.lmm.lme4)
aov.swap_validityTPNP_T1 <- Anova(swap_validityTPNP_T1.lmm.lme4)
```
### T2
```{r swap validity TPNP T2}
d <- data %>% filter(targetContrast==1, nontargetContrast==1, Target==2)
swap_validityTPNP_T2.lmm.lme4 <- lmer(point95_SwapAcc ~ Validity + (1|SID), data = d)
summary(swap_validityTPNP_T2.lmm.lme4)
aov.swap_validityTPNP_T2 <- Anova(swap_validityTPNP_T2.lmm.lme4)
```
## TANP
```{r swap validity TANP}
d <- data %>% filter(targetContrast==0, nontargetContrast==1)
swap_validityTANP.lmm.lme4 <- lmer(point95_SwapAcc ~ Validity + (1|SID), data = d)
summary(swap_validityTANP.lmm.lme4)
aov.swap_validityTANP <- Anova(swap_validityTANP.lmm.lme4)
```
### T1
```{r swap validity TANP T1}
d <- data %>% filter(targetContrast==0, nontargetContrast==1, Target==1)
swap_validityTANP_T1.lmm.lme4 <- lmer(point95_SwapAcc ~ Validity + (1|SID), data = d)
summary(swap_validityTANP_T1.lmm.lme4)
aov.swap_validityTANP_T1 <- Anova(swap_validityTANP_T1.lmm.lme4)
```
### T2
```{r swap validity TANP T2}
d <- data %>% filter(targetContrast==0, nontargetContrast==1, Target==2)
swap_validityTANP_T2.lmm.lme4 <- lmer(point95_SwapAcc ~ Validity + (1|SID), data = d)
summary(swap_validityTANP_T2.lmm.lme4)
aov.swap_validityTANP_T2 <- Anova(swap_validityTANP_T2.lmm.lme4)
```
## TPNA
```{r swap validity TPNA}
d <- data %>% filter(targetContrast==1, nontargetContrast==0)
swap_validityTPNA.lmm.lme4 <- lmer(point95_SwapAcc ~ Validity + (1|SID), data = d)
summary(swap_validityTPNA.lmm.lme4)
aov.swap_validityTPNA <- Anova(swap_validityTPNA.lmm.lme4)
```
### T1
```{r swap validity TPNA T1}
d <- data %>% filter(targetContrast==1, nontargetContrast==1, Target==1)
swap_validityTPNA_T1.lmm.lme4 <- lmer(point95_SwapAcc ~ Validity + (1|SID), data = d)
summary(swap_validityTPNA_T1.lmm.lme4)
aov.swap_validityTPNA_T1 <- Anova(swap_validityTPNA_T1.lmm.lme4)
```
### T2
```{r swap validity TPNA T2}
d <- data %>% filter(targetContrast==1, nontargetContrast==1, Target==2)
swap_validityTPNA_T2.lmm.lme4 <- lmer(point95_SwapAcc ~ Validity + (1|SID), data = d)
summary(swap_validityTPNA_T2.lmm.lme4)
aov.swap_validityTPNA_T2 <- Anova(swap_validityTPNA_T2.lmm.lme4)
```
# target
```{r swap Target only}
d <- data
swap_target.lmm.lme4 <- lmer(point95_SwapAcc ~ Target + (1|SID), data = d)
summary(swap_target.lmm.lme4)
aov.swap_target <- Anova(swap_target.lmm.lme4)
```
## TP
```{r swap target TP}
d <- data %>% filter(targetContrast==1)
swap_targetTP.lmm.lme4 <- lmer(point95_SwapAcc ~ Target + (1|SID), data = d)
summary(swap_targetTP.lmm.lme4)
aov.swap_targetTP <- Anova(swap_targetTP.lmm.lme4)
```
## TA
```{r swap target TA}
d <- data %>% filter(targetContrast==0)
swap_targetTA.lmm.lme4 <- lmer(point95_SwapAcc ~ Target + (1|SID), data = d)
summary(swap_targetTA.lmm.lme4)
aov.swap_targetTA <- Anova(swap_targetTA.lmm.lme4)
```
## TPNP
```{r swap target TPNP}
d <- data %>% filter(targetContrast==1, nontargetContrast==1)
swap_targetTPNP.lmm.lme4 <- lmer(point95_SwapAcc ~ Target + (1|SID), data = d)
summary(swap_targetTPNP.lmm.lme4)
aov.swap_targetTPNP <- Anova(swap_targetTPNP.lmm.lme4)
```

## TANP
```{r swap target TANP}
d <- data %>% filter(targetContrast==0, nontargetContrast==1)
swap_targetTANP.lmm.lme4 <- lmer(point95_SwapAcc ~ Target + (1|SID), data = d)
summary(swap_targetTANP.lmm.lme4)
aov.swap_targetTANP <- Anova(swap_targetTANP.lmm.lme4)
```

## TPNA
```{r swap target TPNA}
d <- data %>% filter(targetContrast==1, nontargetContrast==0)
swap_targetTPNA.lmm.lme4 <- lmer(point95_SwapAcc ~ Target + (1|SID), data = d)
summary(swap_targetTPNA.lmm.lme4)
aov.swap_targetTPNA <- Anova(swap_targetTPNA.lmm.lme4)
```


# target contrast
```{r swap targetContrast only}
d <- data
swap_targetContrast.lmm.lme4 <- lmer(point95_SwapAcc ~ targetContrast + (1|SID), data = d)
summary(swap_targetContrast.lmm.lme4)
aov.swap_targetContrast <- Anova(swap_targetContrast.lmm.lme4)
```
## T1
```{r swap targetContrast T1}
d <- data %>% filter(Target==1)
swap_targetContrastT1.lmm.lme4 <- lmer(point95_SwapAcc ~ targetContrast + (1|SID), data = d)
summary(swap_targetContrastT1.lmm.lme4)
aov.swap_targetContrastT1 <- Anova(swap_targetContrastT1.lmm.lme4)
```
## T2
```{r swap targetContrast T2}
d <- data %>% filter(Target==2)
swap_targetContrastT2.lmm.lme4 <- lmer(point95_SwapAcc ~ targetContrast + (1|SID), data = d)
summary(swap_targetContrastT2.lmm.lme4)
aov.swap_targetContrastT2 <- Anova(swap_targetContrastT2.lmm.lme4)
```
# nontarget contrast
```{r swap nontargetContrast only}
d <- data
swap_nontargetContrast.lmm.lme4 <- lmer(point95_SwapAcc ~ nontargetContrast + (1|SID), data = d)
summary(swap_targetContrast.lmm.lme4)
aov.swap_nontargetContrast <- Anova(swap_nontargetContrast.lmm.lme4)
```
## T1
```{r swap nontargetContrast T1}
d <- data %>% filter(Target==1)
swap_nontargetContrastT1.lmm.lme4 <- lmer(point95_SwapAcc ~ nontargetContrast + (1|SID), data = d)
summary(swap_nontargetContrastT1.lmm.lme4)
aov.swap_nontargetContrastT1 <- Anova(swap_nontargetContrastT1.lmm.lme4)
```
## T2
```{r swap nontargetContrast T2}
d <- data %>% filter(Target==2)
swap_nontargetContrastT2.lmm.lme4 <- lmer(point95_SwapAcc ~ nontargetContrast + (1|SID), data = d)
summary(swap_nontargetContrastT2.lmm.lme4)
aov.swap_nontargetContrastT2 <- Anova(swap_nontargetContrastT2.lmm.lme4)
```